//
// Created by yunp.top on 2020/10/18.
//

#ifndef L05MOVEPOINTS_CONSTANTS_H
#define L05MOVEPOINTS_CONSTANTS_H

#include <SDL.h>

#define WINDOW_WIDTH 550
#define WINDOW_HEIGHT 400
#define RENDERING_MODE SDL_RENDERER_ACCELERATED
#define POINT_COUNT 50000

#endif //L05MOVEPOINTS_CONSTANTS_H
